### PR TITLE
Add bitfield contract for generating random bitfields of arbitrary le…

### PR DESCRIPTION
**Pull request by philipstanislaus**
…ngth

This is a naive implementation of randomly picking `n` bits in a bitfield of length `length`.

The implementation is not yet optimized for gas. Tests run out of gas if we try to pick 300 out of a 1000 bitfield.

Ideas how to improve this implementation: 
1. Track "picked" bits such that a set bit will never be randomly chosen again.
2. Use randomness more efficiently: right now, we use 32 bytes of random data for a position in the bitfield. We could just slice the random data to generate multiple positions out of it.
3. Instead of picking `n` bits, we could also use random data as the initial bitfield, and then randomly add or remove bits. That might be more efficient. 
4. Use inline assembly and work directly on the stack.
5. Alternative approach: shift `n` bits into the bitfield, then swap elements in the bitfield `length` times.

Other open items: 
- [ ] transform into a library, make usable on `uint256[]`
- [ ] add docs

Happy to hear your thoughts!

### CODE REVIEW

**Comment by philipstanislaus** [comment]
Contract now deals with a prior bitfield, and only samples from the set bits within that `prior`. 

Added 2 methods for that: 

1. `randomNBitsFromPriorCounting` counts the number of set bits in the `prior`, then draws a random number lower than that count, finds the corresponding index, and sets it to true. Repeats that `n` times.
2. `randomNBitsFromPriorRejectionSampling` draws a random number, derives an index in the bitfield, and sets the bit if it is in the `prior` and not yet set. Repeats that `n` times.

Gas usage: 

1. With a check whether `n` is smaller than the set bits:
    1a) Rejection sampling: `288,628` gas
    1b) Counting: `2,659,621` gas

2. Without a check whether `n` is smaller than the set bits:
    2a) Rejection sampling: `55,314` gas
    2b) Counting: `2,659,595` gas

Reason why counting is that much more expensive are loops that are getting the index in the bitset for the nth validator. That can be improved by pre-calculating the index and storing it, and by rewriting the bit operations in inline assembly.

**Comment by philipstanislaus** [comment]
gas `countSetBitsNaive`: 257,258
gas `countSetShift`: 285,060
gas `countSetBitsKernighan`: 209,326
gas `countSetBitsHammingWeight`: 24,247

**Comment by musnit** [comment]
@philipstanislaus awesome thanks. happy to merge this in, though i would still like to review it myself when we're done with existing pressing changes - added an issue for that: https://github.com/Snowfork/polkadot-ethereum/issues/270

**Comment by philipstanislaus** [comment]
@musnit just merged it into your branch, so no harm taken ;)

**Pull request merged**
