### PR TITLE
Blake2b test code from Olaf

### PR DESCRIPTION
**Pull request by musnit**

### CODE REVIEW

**Comment by musnit** [comment]
@denalimarsh @philipstanislaus added you to this for review for context and specifically @philipstanislaus to sanity check if the code which does 12 rounds of hashing fits the same hashing we'd need for our Parachain header.

**Review by philipstanislaus — COMMENTED** [review]
This code seems to be from: https://eips.ethereum.org/EIPS/eip-152

**Review by philipstanislaus — COMMENTED** [review]
What has been implemented here is the compression function `F` of blake2b, not the whole blake2b algorithm. Few points are open to get the correct implementation for blake2b hashing:

1. Initialization of the state vector should be double checked, see https://en.wikipedia.org/wiki/BLAKE_(hash_function)#Initialization_vector 
2. The compression function of the blake2b algorithm is called for 128 bit words of the message, and will be called differently on the last chunk. The code above only does that last call of the compression function. The logic here should be adjusted according to: https://en.wikipedia.org/wiki/BLAKE_(hash_function)#BLAKE2b_algorithm

Since we are most likely not using blake2b anyways, I'd suggest holding off working on those tasks. Additionally, https://eips.ethereum.org/EIPS/eip-152 already contains gas estimates, namely 12 gas per started 128 word of the message.

**Comment by musnit** [comment]
Thanks for double checking - yeh in that case we can assume the cost will be even higher than for the above code and so agreed hold off for now

**Pull request merged**
